Require Export Functor.
Require Export NaturalTransformation.Core NaturalTransformation.Identity NaturalTransformation.Composition NaturalTransformation.CompositionLaws NaturalTransformation.Equality.
