language: c
env:
 - secure: "xQl3rzBR99zDyI42BEu/8aWArZV6hu1uC41MsIgo4vRDHOfkmEIEbLNmp25oqPjQPVhFRA7YNpcCmjjlgPcIH8YhWwcQkJwdA8JYZ2RFOVcv1ngPfC3tYDu1suzoRZXPSGp/LgAn48MPYf3dAMJvChTX2mE1m9z2P6fkSpkwsnk="
before_script:
 - sudo apt-get update -q
 - sudo apt-get install -q ocaml camlp5 time
 - git clone --depth=5 --branch=trunk git://github.com/HoTT/coq.git coq-HoTT
 - pushd coq-HoTT
 -   ./configure -prefix /usr/local -debug -no-native-compiler
 -   make coqlight
 -   sudo make install-coqlight
 - popd
script: "make pretty-timed -j5"
after_success: "./etc/ci/after_success.sh"
